name: OpenCV CUDA

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build-ubuntu18_04:
    name: Build OpenCV 3.4.14 with CUDA 11.3.1 on Ubuntu 18.04
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push OpenCV CUDA to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=registry,ref=ghcr.io/zhouchengcom/opencv-cuda-docker:ubuntu18.04-cuda11.3.1-opencv3.4.14
          cache-to: type=inline
          tags: |
            zhouchengcom/opencv-cuda:ubuntu18.04-cuda11.3.1-opencv3.4.14
            ghcr.io/zhouchengcom/opencv-cuda-docker:ubuntu18.04-cuda11.3.1-opencv3.4.14
          build-args: |
            UBUNTU=18.04
            CUDA=11.3.1
            OPENCV=3.4.14
      
      - name: Build and Push OpenCV CUDA ROS to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.ros-melodic
          push: true
          cache-from: type=registry,ref=ghcr.io/zhouchengcom/opencv-cuda-docker:ubuntu18.04-cuda11.3.1-opencv3.4.14-rosmelodic
          cache-to: type=inline
          tags: |
            zhouchengcom/opencv-cuda:ubuntu18.04-cuda11.3.1-opencv3.4.14-rosmelodic
            ghcr.io/zhouchengcom/opencv-cuda-docker:ubuntu18.04-cuda11.3.1-opencv3.4.14-rosmelodic
          build-args: |
            UBUNTU=18.04
            CUDA=11.3.1
            OPENCV=3.4.14

  build-ubuntu20_04:
    name: Build OpenCV 4.5.3 with CUDA 11.3.1 on Ubuntu 20.04
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push OpenCV CUDA to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=registry,ref=ghcr.io/zhouchengcom/opencv-cuda-docker:ubuntu20.04-cuda11.3.1-opencv4.5.3
          cache-to: type=inline
          tags: |
            zhouchengcom/opencv-cuda:ubuntu20.04-cuda11.3.1-opencv4.5.3
            zhouchengcom/opencv-cuda:latest
            ghcr.io/zhouchengcom/opencv-cuda-docker:ubuntu20.04-cuda11.3.1-opencv4.5.3
            ghcr.io/zhouchengcom/opencv-cuda-docker:latest
          build-args: |
            UBUNTU=20.04
            CUDA=11.3.1
            OPENCV=4.5.3

      - name: Build and Push OpenCV CUDA ROS to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.ros-noetic
          push: true
          cache-from: type=registry,ref=ghcr.io/zhouchengcom/opencv-cuda-docker:ubuntu20.04-cuda11.3.1-opencv4.5.3-rosnoetic
          cache-to: type=inline
          tags: |
            zhouchengcom/opencv-cuda:ubuntu20.04-cuda11.3.1-opencv4.5.3-rosnoetic
            zhouchengcom/opencv-cuda:ros-latest
            ghcr.io/zhouchengcom/opencv-cuda-docker:ubuntu20.04-cuda11.3.1-opencv4.5.3-rosnoetic
            ghcr.io/zhouchengcom/opencv-cuda-docker:ros-latest
          build-args: |
            UBUNTU=20.04
            CUDA=11.3.1
            OPENCV=4.5.3
